#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: nginx-deployment
#  labels:
#    app: nginx
#spec:
#  replicas: 3
#  selector:
#    matchLabels:
#      app: nginx
#  template:
#    metadata:
#      labels:
#        app: nginx
#    spec:
#      containers:
#      - name: nginx
#        #image: nginx:1.14.2
#        image: otp-api-docker.jar 
#        ports:
#        - containerPort: 80
#        
#---
#apiVersion: v1
#kind: Service
#metadata: 
#  name: otp-test-service
#  labels:
#    app: otp-test
#spec:
#  #replicas: 3
#  selector:
#    #matchLabels:
#    app: otp-test
#  #template:
#    #metadata:
#      #labels:
#        #app: otp-test
#    #spec:
#     # containers:
#      #- name: otp-test
#       # image: otp-api-docker.jar
#    ports: 9090
#    #- containerPort : 9090
##    ports:
##    - protocol: "TCP"
##      port: 9090 # The port that the service is running on in the cluster
##      targetPort: 9090
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-generation
  namespace: interns-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: otp-generation
        image: aarush73/new_otp_file:latest
---
apiVersion: v1
kind: Service
metadata:
  name: otp-service
  namespace: interns-dev
spec:
  type: NodePort
#  replicas: 3
  selector:
    bb: web
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30004